repositories:
- name: css
  url: https://communitysolidserver.github.io/css-helm-chart/

environments:
  production:
  staging:

releases:
  - name: itme-image-pull-secrets
    namespace: mysilio-me
    chart: ./image-pull-secrets
    values:
      - ./values/image-pull-secrets.yaml.gotmpl
  - name: {{ .Environment.Name }}-css
    namespace: mysilio-me
    chart: css/community-solid-server
    version: 2.1.0
    values:
      - ./values/{{ .Environment.Name }}.yaml.gotmpl
    needs:
      - mysilio-me/itme-image-pull-secrets
